// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: linoleum/tracing.proto

package io.github.demiourgoi.linoleum.messages;

/**
 * <pre>
 * A span paired with all the context information associated to it on
 * a parent TracesData message returned in a stream in Jaeger's response to a call to `FindTraces`
 * </pre>
 *
 * Protobuf type {@code demiourgoi.linoleum.messages.SpanInfo}
 */
public final class SpanInfo extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:demiourgoi.linoleum.messages.SpanInfo)
    SpanInfoOrBuilder {
private static final long serialVersionUID = 0L;
  // Use SpanInfo.newBuilder() to construct.
  private SpanInfo(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private SpanInfo() {
    scopeSchemaUrl_ = "";
    resourceSchemaUrl_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new SpanInfo();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private SpanInfo(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            io.opentelemetry.proto.trace.v1.Span.Builder subBuilder = null;
            if (span_ != null) {
              subBuilder = span_.toBuilder();
            }
            span_ = input.readMessage(io.opentelemetry.proto.trace.v1.Span.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(span_);
              span_ = subBuilder.buildPartial();
            }

            break;
          }
          case 18: {
            io.opentelemetry.proto.common.v1.InstrumentationScope.Builder subBuilder = null;
            if (scope_ != null) {
              subBuilder = scope_.toBuilder();
            }
            scope_ = input.readMessage(io.opentelemetry.proto.common.v1.InstrumentationScope.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(scope_);
              scope_ = subBuilder.buildPartial();
            }

            break;
          }
          case 26: {
            java.lang.String s = input.readStringRequireUtf8();

            scopeSchemaUrl_ = s;
            break;
          }
          case 34: {
            io.opentelemetry.proto.resource.v1.Resource.Builder subBuilder = null;
            if (resource_ != null) {
              subBuilder = resource_.toBuilder();
            }
            resource_ = input.readMessage(io.opentelemetry.proto.resource.v1.Resource.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(resource_);
              resource_ = subBuilder.buildPartial();
            }

            break;
          }
          case 42: {
            java.lang.String s = input.readStringRequireUtf8();

            resourceSchemaUrl_ = s;
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return io.github.demiourgoi.linoleum.messages.Tracing.internal_static_demiourgoi_linoleum_messages_SpanInfo_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return io.github.demiourgoi.linoleum.messages.Tracing.internal_static_demiourgoi_linoleum_messages_SpanInfo_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            io.github.demiourgoi.linoleum.messages.SpanInfo.class, io.github.demiourgoi.linoleum.messages.SpanInfo.Builder.class);
  }

  public static final int SPAN_FIELD_NUMBER = 1;
  private io.opentelemetry.proto.trace.v1.Span span_;
  /**
   * <code>.opentelemetry.proto.trace.v1.Span span = 1;</code>
   * @return Whether the span field is set.
   */
  @java.lang.Override
  public boolean hasSpan() {
    return span_ != null;
  }
  /**
   * <code>.opentelemetry.proto.trace.v1.Span span = 1;</code>
   * @return The span.
   */
  @java.lang.Override
  public io.opentelemetry.proto.trace.v1.Span getSpan() {
    return span_ == null ? io.opentelemetry.proto.trace.v1.Span.getDefaultInstance() : span_;
  }
  /**
   * <code>.opentelemetry.proto.trace.v1.Span span = 1;</code>
   */
  @java.lang.Override
  public io.opentelemetry.proto.trace.v1.SpanOrBuilder getSpanOrBuilder() {
    return getSpan();
  }

  public static final int SCOPE_FIELD_NUMBER = 2;
  private io.opentelemetry.proto.common.v1.InstrumentationScope scope_;
  /**
   * <code>.opentelemetry.proto.common.v1.InstrumentationScope scope = 2;</code>
   * @return Whether the scope field is set.
   */
  @java.lang.Override
  public boolean hasScope() {
    return scope_ != null;
  }
  /**
   * <code>.opentelemetry.proto.common.v1.InstrumentationScope scope = 2;</code>
   * @return The scope.
   */
  @java.lang.Override
  public io.opentelemetry.proto.common.v1.InstrumentationScope getScope() {
    return scope_ == null ? io.opentelemetry.proto.common.v1.InstrumentationScope.getDefaultInstance() : scope_;
  }
  /**
   * <code>.opentelemetry.proto.common.v1.InstrumentationScope scope = 2;</code>
   */
  @java.lang.Override
  public io.opentelemetry.proto.common.v1.InstrumentationScopeOrBuilder getScopeOrBuilder() {
    return getScope();
  }

  public static final int SCOPE_SCHEMA_URL_FIELD_NUMBER = 3;
  private volatile java.lang.Object scopeSchemaUrl_;
  /**
   * <pre>
   * field schema_url in the parent ScopeSpans message
   * </pre>
   *
   * <code>string scope_schema_url = 3;</code>
   * @return The scopeSchemaUrl.
   */
  @java.lang.Override
  public java.lang.String getScopeSchemaUrl() {
    java.lang.Object ref = scopeSchemaUrl_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      scopeSchemaUrl_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * field schema_url in the parent ScopeSpans message
   * </pre>
   *
   * <code>string scope_schema_url = 3;</code>
   * @return The bytes for scopeSchemaUrl.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getScopeSchemaUrlBytes() {
    java.lang.Object ref = scopeSchemaUrl_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      scopeSchemaUrl_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int RESOURCE_FIELD_NUMBER = 4;
  private io.opentelemetry.proto.resource.v1.Resource resource_;
  /**
   * <code>.opentelemetry.proto.resource.v1.Resource resource = 4;</code>
   * @return Whether the resource field is set.
   */
  @java.lang.Override
  public boolean hasResource() {
    return resource_ != null;
  }
  /**
   * <code>.opentelemetry.proto.resource.v1.Resource resource = 4;</code>
   * @return The resource.
   */
  @java.lang.Override
  public io.opentelemetry.proto.resource.v1.Resource getResource() {
    return resource_ == null ? io.opentelemetry.proto.resource.v1.Resource.getDefaultInstance() : resource_;
  }
  /**
   * <code>.opentelemetry.proto.resource.v1.Resource resource = 4;</code>
   */
  @java.lang.Override
  public io.opentelemetry.proto.resource.v1.ResourceOrBuilder getResourceOrBuilder() {
    return getResource();
  }

  public static final int RESOURCE_SCHEMA_URL_FIELD_NUMBER = 5;
  private volatile java.lang.Object resourceSchemaUrl_;
  /**
   * <pre>
   * field schema_url in the parent ResourceSpans message
   * </pre>
   *
   * <code>string resource_schema_url = 5;</code>
   * @return The resourceSchemaUrl.
   */
  @java.lang.Override
  public java.lang.String getResourceSchemaUrl() {
    java.lang.Object ref = resourceSchemaUrl_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      resourceSchemaUrl_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * field schema_url in the parent ResourceSpans message
   * </pre>
   *
   * <code>string resource_schema_url = 5;</code>
   * @return The bytes for resourceSchemaUrl.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getResourceSchemaUrlBytes() {
    java.lang.Object ref = resourceSchemaUrl_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      resourceSchemaUrl_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (span_ != null) {
      output.writeMessage(1, getSpan());
    }
    if (scope_ != null) {
      output.writeMessage(2, getScope());
    }
    if (!getScopeSchemaUrlBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, scopeSchemaUrl_);
    }
    if (resource_ != null) {
      output.writeMessage(4, getResource());
    }
    if (!getResourceSchemaUrlBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 5, resourceSchemaUrl_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (span_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getSpan());
    }
    if (scope_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, getScope());
    }
    if (!getScopeSchemaUrlBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, scopeSchemaUrl_);
    }
    if (resource_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(4, getResource());
    }
    if (!getResourceSchemaUrlBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, resourceSchemaUrl_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof io.github.demiourgoi.linoleum.messages.SpanInfo)) {
      return super.equals(obj);
    }
    io.github.demiourgoi.linoleum.messages.SpanInfo other = (io.github.demiourgoi.linoleum.messages.SpanInfo) obj;

    if (hasSpan() != other.hasSpan()) return false;
    if (hasSpan()) {
      if (!getSpan()
          .equals(other.getSpan())) return false;
    }
    if (hasScope() != other.hasScope()) return false;
    if (hasScope()) {
      if (!getScope()
          .equals(other.getScope())) return false;
    }
    if (!getScopeSchemaUrl()
        .equals(other.getScopeSchemaUrl())) return false;
    if (hasResource() != other.hasResource()) return false;
    if (hasResource()) {
      if (!getResource()
          .equals(other.getResource())) return false;
    }
    if (!getResourceSchemaUrl()
        .equals(other.getResourceSchemaUrl())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasSpan()) {
      hash = (37 * hash) + SPAN_FIELD_NUMBER;
      hash = (53 * hash) + getSpan().hashCode();
    }
    if (hasScope()) {
      hash = (37 * hash) + SCOPE_FIELD_NUMBER;
      hash = (53 * hash) + getScope().hashCode();
    }
    hash = (37 * hash) + SCOPE_SCHEMA_URL_FIELD_NUMBER;
    hash = (53 * hash) + getScopeSchemaUrl().hashCode();
    if (hasResource()) {
      hash = (37 * hash) + RESOURCE_FIELD_NUMBER;
      hash = (53 * hash) + getResource().hashCode();
    }
    hash = (37 * hash) + RESOURCE_SCHEMA_URL_FIELD_NUMBER;
    hash = (53 * hash) + getResourceSchemaUrl().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static io.github.demiourgoi.linoleum.messages.SpanInfo parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.github.demiourgoi.linoleum.messages.SpanInfo parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.github.demiourgoi.linoleum.messages.SpanInfo parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.github.demiourgoi.linoleum.messages.SpanInfo parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.github.demiourgoi.linoleum.messages.SpanInfo parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.github.demiourgoi.linoleum.messages.SpanInfo parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.github.demiourgoi.linoleum.messages.SpanInfo parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static io.github.demiourgoi.linoleum.messages.SpanInfo parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static io.github.demiourgoi.linoleum.messages.SpanInfo parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static io.github.demiourgoi.linoleum.messages.SpanInfo parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static io.github.demiourgoi.linoleum.messages.SpanInfo parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static io.github.demiourgoi.linoleum.messages.SpanInfo parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(io.github.demiourgoi.linoleum.messages.SpanInfo prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * A span paired with all the context information associated to it on
   * a parent TracesData message returned in a stream in Jaeger's response to a call to `FindTraces`
   * </pre>
   *
   * Protobuf type {@code demiourgoi.linoleum.messages.SpanInfo}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:demiourgoi.linoleum.messages.SpanInfo)
      io.github.demiourgoi.linoleum.messages.SpanInfoOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return io.github.demiourgoi.linoleum.messages.Tracing.internal_static_demiourgoi_linoleum_messages_SpanInfo_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return io.github.demiourgoi.linoleum.messages.Tracing.internal_static_demiourgoi_linoleum_messages_SpanInfo_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              io.github.demiourgoi.linoleum.messages.SpanInfo.class, io.github.demiourgoi.linoleum.messages.SpanInfo.Builder.class);
    }

    // Construct using io.github.demiourgoi.linoleum.messages.SpanInfo.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      if (spanBuilder_ == null) {
        span_ = null;
      } else {
        span_ = null;
        spanBuilder_ = null;
      }
      if (scopeBuilder_ == null) {
        scope_ = null;
      } else {
        scope_ = null;
        scopeBuilder_ = null;
      }
      scopeSchemaUrl_ = "";

      if (resourceBuilder_ == null) {
        resource_ = null;
      } else {
        resource_ = null;
        resourceBuilder_ = null;
      }
      resourceSchemaUrl_ = "";

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return io.github.demiourgoi.linoleum.messages.Tracing.internal_static_demiourgoi_linoleum_messages_SpanInfo_descriptor;
    }

    @java.lang.Override
    public io.github.demiourgoi.linoleum.messages.SpanInfo getDefaultInstanceForType() {
      return io.github.demiourgoi.linoleum.messages.SpanInfo.getDefaultInstance();
    }

    @java.lang.Override
    public io.github.demiourgoi.linoleum.messages.SpanInfo build() {
      io.github.demiourgoi.linoleum.messages.SpanInfo result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public io.github.demiourgoi.linoleum.messages.SpanInfo buildPartial() {
      io.github.demiourgoi.linoleum.messages.SpanInfo result = new io.github.demiourgoi.linoleum.messages.SpanInfo(this);
      if (spanBuilder_ == null) {
        result.span_ = span_;
      } else {
        result.span_ = spanBuilder_.build();
      }
      if (scopeBuilder_ == null) {
        result.scope_ = scope_;
      } else {
        result.scope_ = scopeBuilder_.build();
      }
      result.scopeSchemaUrl_ = scopeSchemaUrl_;
      if (resourceBuilder_ == null) {
        result.resource_ = resource_;
      } else {
        result.resource_ = resourceBuilder_.build();
      }
      result.resourceSchemaUrl_ = resourceSchemaUrl_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof io.github.demiourgoi.linoleum.messages.SpanInfo) {
        return mergeFrom((io.github.demiourgoi.linoleum.messages.SpanInfo)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(io.github.demiourgoi.linoleum.messages.SpanInfo other) {
      if (other == io.github.demiourgoi.linoleum.messages.SpanInfo.getDefaultInstance()) return this;
      if (other.hasSpan()) {
        mergeSpan(other.getSpan());
      }
      if (other.hasScope()) {
        mergeScope(other.getScope());
      }
      if (!other.getScopeSchemaUrl().isEmpty()) {
        scopeSchemaUrl_ = other.scopeSchemaUrl_;
        onChanged();
      }
      if (other.hasResource()) {
        mergeResource(other.getResource());
      }
      if (!other.getResourceSchemaUrl().isEmpty()) {
        resourceSchemaUrl_ = other.resourceSchemaUrl_;
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      io.github.demiourgoi.linoleum.messages.SpanInfo parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (io.github.demiourgoi.linoleum.messages.SpanInfo) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private io.opentelemetry.proto.trace.v1.Span span_;
    private com.google.protobuf.SingleFieldBuilderV3<
        io.opentelemetry.proto.trace.v1.Span, io.opentelemetry.proto.trace.v1.Span.Builder, io.opentelemetry.proto.trace.v1.SpanOrBuilder> spanBuilder_;
    /**
     * <code>.opentelemetry.proto.trace.v1.Span span = 1;</code>
     * @return Whether the span field is set.
     */
    public boolean hasSpan() {
      return spanBuilder_ != null || span_ != null;
    }
    /**
     * <code>.opentelemetry.proto.trace.v1.Span span = 1;</code>
     * @return The span.
     */
    public io.opentelemetry.proto.trace.v1.Span getSpan() {
      if (spanBuilder_ == null) {
        return span_ == null ? io.opentelemetry.proto.trace.v1.Span.getDefaultInstance() : span_;
      } else {
        return spanBuilder_.getMessage();
      }
    }
    /**
     * <code>.opentelemetry.proto.trace.v1.Span span = 1;</code>
     */
    public Builder setSpan(io.opentelemetry.proto.trace.v1.Span value) {
      if (spanBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        span_ = value;
        onChanged();
      } else {
        spanBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.opentelemetry.proto.trace.v1.Span span = 1;</code>
     */
    public Builder setSpan(
        io.opentelemetry.proto.trace.v1.Span.Builder builderForValue) {
      if (spanBuilder_ == null) {
        span_ = builderForValue.build();
        onChanged();
      } else {
        spanBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.opentelemetry.proto.trace.v1.Span span = 1;</code>
     */
    public Builder mergeSpan(io.opentelemetry.proto.trace.v1.Span value) {
      if (spanBuilder_ == null) {
        if (span_ != null) {
          span_ =
            io.opentelemetry.proto.trace.v1.Span.newBuilder(span_).mergeFrom(value).buildPartial();
        } else {
          span_ = value;
        }
        onChanged();
      } else {
        spanBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.opentelemetry.proto.trace.v1.Span span = 1;</code>
     */
    public Builder clearSpan() {
      if (spanBuilder_ == null) {
        span_ = null;
        onChanged();
      } else {
        span_ = null;
        spanBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.opentelemetry.proto.trace.v1.Span span = 1;</code>
     */
    public io.opentelemetry.proto.trace.v1.Span.Builder getSpanBuilder() {
      
      onChanged();
      return getSpanFieldBuilder().getBuilder();
    }
    /**
     * <code>.opentelemetry.proto.trace.v1.Span span = 1;</code>
     */
    public io.opentelemetry.proto.trace.v1.SpanOrBuilder getSpanOrBuilder() {
      if (spanBuilder_ != null) {
        return spanBuilder_.getMessageOrBuilder();
      } else {
        return span_ == null ?
            io.opentelemetry.proto.trace.v1.Span.getDefaultInstance() : span_;
      }
    }
    /**
     * <code>.opentelemetry.proto.trace.v1.Span span = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        io.opentelemetry.proto.trace.v1.Span, io.opentelemetry.proto.trace.v1.Span.Builder, io.opentelemetry.proto.trace.v1.SpanOrBuilder> 
        getSpanFieldBuilder() {
      if (spanBuilder_ == null) {
        spanBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            io.opentelemetry.proto.trace.v1.Span, io.opentelemetry.proto.trace.v1.Span.Builder, io.opentelemetry.proto.trace.v1.SpanOrBuilder>(
                getSpan(),
                getParentForChildren(),
                isClean());
        span_ = null;
      }
      return spanBuilder_;
    }

    private io.opentelemetry.proto.common.v1.InstrumentationScope scope_;
    private com.google.protobuf.SingleFieldBuilderV3<
        io.opentelemetry.proto.common.v1.InstrumentationScope, io.opentelemetry.proto.common.v1.InstrumentationScope.Builder, io.opentelemetry.proto.common.v1.InstrumentationScopeOrBuilder> scopeBuilder_;
    /**
     * <code>.opentelemetry.proto.common.v1.InstrumentationScope scope = 2;</code>
     * @return Whether the scope field is set.
     */
    public boolean hasScope() {
      return scopeBuilder_ != null || scope_ != null;
    }
    /**
     * <code>.opentelemetry.proto.common.v1.InstrumentationScope scope = 2;</code>
     * @return The scope.
     */
    public io.opentelemetry.proto.common.v1.InstrumentationScope getScope() {
      if (scopeBuilder_ == null) {
        return scope_ == null ? io.opentelemetry.proto.common.v1.InstrumentationScope.getDefaultInstance() : scope_;
      } else {
        return scopeBuilder_.getMessage();
      }
    }
    /**
     * <code>.opentelemetry.proto.common.v1.InstrumentationScope scope = 2;</code>
     */
    public Builder setScope(io.opentelemetry.proto.common.v1.InstrumentationScope value) {
      if (scopeBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        scope_ = value;
        onChanged();
      } else {
        scopeBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.opentelemetry.proto.common.v1.InstrumentationScope scope = 2;</code>
     */
    public Builder setScope(
        io.opentelemetry.proto.common.v1.InstrumentationScope.Builder builderForValue) {
      if (scopeBuilder_ == null) {
        scope_ = builderForValue.build();
        onChanged();
      } else {
        scopeBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.opentelemetry.proto.common.v1.InstrumentationScope scope = 2;</code>
     */
    public Builder mergeScope(io.opentelemetry.proto.common.v1.InstrumentationScope value) {
      if (scopeBuilder_ == null) {
        if (scope_ != null) {
          scope_ =
            io.opentelemetry.proto.common.v1.InstrumentationScope.newBuilder(scope_).mergeFrom(value).buildPartial();
        } else {
          scope_ = value;
        }
        onChanged();
      } else {
        scopeBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.opentelemetry.proto.common.v1.InstrumentationScope scope = 2;</code>
     */
    public Builder clearScope() {
      if (scopeBuilder_ == null) {
        scope_ = null;
        onChanged();
      } else {
        scope_ = null;
        scopeBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.opentelemetry.proto.common.v1.InstrumentationScope scope = 2;</code>
     */
    public io.opentelemetry.proto.common.v1.InstrumentationScope.Builder getScopeBuilder() {
      
      onChanged();
      return getScopeFieldBuilder().getBuilder();
    }
    /**
     * <code>.opentelemetry.proto.common.v1.InstrumentationScope scope = 2;</code>
     */
    public io.opentelemetry.proto.common.v1.InstrumentationScopeOrBuilder getScopeOrBuilder() {
      if (scopeBuilder_ != null) {
        return scopeBuilder_.getMessageOrBuilder();
      } else {
        return scope_ == null ?
            io.opentelemetry.proto.common.v1.InstrumentationScope.getDefaultInstance() : scope_;
      }
    }
    /**
     * <code>.opentelemetry.proto.common.v1.InstrumentationScope scope = 2;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        io.opentelemetry.proto.common.v1.InstrumentationScope, io.opentelemetry.proto.common.v1.InstrumentationScope.Builder, io.opentelemetry.proto.common.v1.InstrumentationScopeOrBuilder> 
        getScopeFieldBuilder() {
      if (scopeBuilder_ == null) {
        scopeBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            io.opentelemetry.proto.common.v1.InstrumentationScope, io.opentelemetry.proto.common.v1.InstrumentationScope.Builder, io.opentelemetry.proto.common.v1.InstrumentationScopeOrBuilder>(
                getScope(),
                getParentForChildren(),
                isClean());
        scope_ = null;
      }
      return scopeBuilder_;
    }

    private java.lang.Object scopeSchemaUrl_ = "";
    /**
     * <pre>
     * field schema_url in the parent ScopeSpans message
     * </pre>
     *
     * <code>string scope_schema_url = 3;</code>
     * @return The scopeSchemaUrl.
     */
    public java.lang.String getScopeSchemaUrl() {
      java.lang.Object ref = scopeSchemaUrl_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        scopeSchemaUrl_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * field schema_url in the parent ScopeSpans message
     * </pre>
     *
     * <code>string scope_schema_url = 3;</code>
     * @return The bytes for scopeSchemaUrl.
     */
    public com.google.protobuf.ByteString
        getScopeSchemaUrlBytes() {
      java.lang.Object ref = scopeSchemaUrl_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        scopeSchemaUrl_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * field schema_url in the parent ScopeSpans message
     * </pre>
     *
     * <code>string scope_schema_url = 3;</code>
     * @param value The scopeSchemaUrl to set.
     * @return This builder for chaining.
     */
    public Builder setScopeSchemaUrl(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      scopeSchemaUrl_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * field schema_url in the parent ScopeSpans message
     * </pre>
     *
     * <code>string scope_schema_url = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearScopeSchemaUrl() {
      
      scopeSchemaUrl_ = getDefaultInstance().getScopeSchemaUrl();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * field schema_url in the parent ScopeSpans message
     * </pre>
     *
     * <code>string scope_schema_url = 3;</code>
     * @param value The bytes for scopeSchemaUrl to set.
     * @return This builder for chaining.
     */
    public Builder setScopeSchemaUrlBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      scopeSchemaUrl_ = value;
      onChanged();
      return this;
    }

    private io.opentelemetry.proto.resource.v1.Resource resource_;
    private com.google.protobuf.SingleFieldBuilderV3<
        io.opentelemetry.proto.resource.v1.Resource, io.opentelemetry.proto.resource.v1.Resource.Builder, io.opentelemetry.proto.resource.v1.ResourceOrBuilder> resourceBuilder_;
    /**
     * <code>.opentelemetry.proto.resource.v1.Resource resource = 4;</code>
     * @return Whether the resource field is set.
     */
    public boolean hasResource() {
      return resourceBuilder_ != null || resource_ != null;
    }
    /**
     * <code>.opentelemetry.proto.resource.v1.Resource resource = 4;</code>
     * @return The resource.
     */
    public io.opentelemetry.proto.resource.v1.Resource getResource() {
      if (resourceBuilder_ == null) {
        return resource_ == null ? io.opentelemetry.proto.resource.v1.Resource.getDefaultInstance() : resource_;
      } else {
        return resourceBuilder_.getMessage();
      }
    }
    /**
     * <code>.opentelemetry.proto.resource.v1.Resource resource = 4;</code>
     */
    public Builder setResource(io.opentelemetry.proto.resource.v1.Resource value) {
      if (resourceBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        resource_ = value;
        onChanged();
      } else {
        resourceBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.opentelemetry.proto.resource.v1.Resource resource = 4;</code>
     */
    public Builder setResource(
        io.opentelemetry.proto.resource.v1.Resource.Builder builderForValue) {
      if (resourceBuilder_ == null) {
        resource_ = builderForValue.build();
        onChanged();
      } else {
        resourceBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.opentelemetry.proto.resource.v1.Resource resource = 4;</code>
     */
    public Builder mergeResource(io.opentelemetry.proto.resource.v1.Resource value) {
      if (resourceBuilder_ == null) {
        if (resource_ != null) {
          resource_ =
            io.opentelemetry.proto.resource.v1.Resource.newBuilder(resource_).mergeFrom(value).buildPartial();
        } else {
          resource_ = value;
        }
        onChanged();
      } else {
        resourceBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.opentelemetry.proto.resource.v1.Resource resource = 4;</code>
     */
    public Builder clearResource() {
      if (resourceBuilder_ == null) {
        resource_ = null;
        onChanged();
      } else {
        resource_ = null;
        resourceBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.opentelemetry.proto.resource.v1.Resource resource = 4;</code>
     */
    public io.opentelemetry.proto.resource.v1.Resource.Builder getResourceBuilder() {
      
      onChanged();
      return getResourceFieldBuilder().getBuilder();
    }
    /**
     * <code>.opentelemetry.proto.resource.v1.Resource resource = 4;</code>
     */
    public io.opentelemetry.proto.resource.v1.ResourceOrBuilder getResourceOrBuilder() {
      if (resourceBuilder_ != null) {
        return resourceBuilder_.getMessageOrBuilder();
      } else {
        return resource_ == null ?
            io.opentelemetry.proto.resource.v1.Resource.getDefaultInstance() : resource_;
      }
    }
    /**
     * <code>.opentelemetry.proto.resource.v1.Resource resource = 4;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        io.opentelemetry.proto.resource.v1.Resource, io.opentelemetry.proto.resource.v1.Resource.Builder, io.opentelemetry.proto.resource.v1.ResourceOrBuilder> 
        getResourceFieldBuilder() {
      if (resourceBuilder_ == null) {
        resourceBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            io.opentelemetry.proto.resource.v1.Resource, io.opentelemetry.proto.resource.v1.Resource.Builder, io.opentelemetry.proto.resource.v1.ResourceOrBuilder>(
                getResource(),
                getParentForChildren(),
                isClean());
        resource_ = null;
      }
      return resourceBuilder_;
    }

    private java.lang.Object resourceSchemaUrl_ = "";
    /**
     * <pre>
     * field schema_url in the parent ResourceSpans message
     * </pre>
     *
     * <code>string resource_schema_url = 5;</code>
     * @return The resourceSchemaUrl.
     */
    public java.lang.String getResourceSchemaUrl() {
      java.lang.Object ref = resourceSchemaUrl_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        resourceSchemaUrl_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * field schema_url in the parent ResourceSpans message
     * </pre>
     *
     * <code>string resource_schema_url = 5;</code>
     * @return The bytes for resourceSchemaUrl.
     */
    public com.google.protobuf.ByteString
        getResourceSchemaUrlBytes() {
      java.lang.Object ref = resourceSchemaUrl_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        resourceSchemaUrl_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * field schema_url in the parent ResourceSpans message
     * </pre>
     *
     * <code>string resource_schema_url = 5;</code>
     * @param value The resourceSchemaUrl to set.
     * @return This builder for chaining.
     */
    public Builder setResourceSchemaUrl(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      resourceSchemaUrl_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * field schema_url in the parent ResourceSpans message
     * </pre>
     *
     * <code>string resource_schema_url = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearResourceSchemaUrl() {
      
      resourceSchemaUrl_ = getDefaultInstance().getResourceSchemaUrl();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * field schema_url in the parent ResourceSpans message
     * </pre>
     *
     * <code>string resource_schema_url = 5;</code>
     * @param value The bytes for resourceSchemaUrl to set.
     * @return This builder for chaining.
     */
    public Builder setResourceSchemaUrlBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      resourceSchemaUrl_ = value;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:demiourgoi.linoleum.messages.SpanInfo)
  }

  // @@protoc_insertion_point(class_scope:demiourgoi.linoleum.messages.SpanInfo)
  private static final io.github.demiourgoi.linoleum.messages.SpanInfo DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new io.github.demiourgoi.linoleum.messages.SpanInfo();
  }

  public static io.github.demiourgoi.linoleum.messages.SpanInfo getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<SpanInfo>
      PARSER = new com.google.protobuf.AbstractParser<SpanInfo>() {
    @java.lang.Override
    public SpanInfo parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new SpanInfo(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<SpanInfo> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<SpanInfo> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public io.github.demiourgoi.linoleum.messages.SpanInfo getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

