/*
 * This file was generated by the Gradle 'init' task.
 *
 * The settings file is used to specify which projects to include in your build.
 * For more detailed information on multi-project builds, please refer to https://docs.gradle.org/8.10.2/userguide/multi_project_builds.html in the Gradle documentation.
 */

plugins {
    // Apply the foojay-resolver plugin to allow automatic download of JDKs
    id("org.gradle.toolchains.foojay-resolver-convention") version "0.8.0"

    id("com.gradle.develocity") version "3.17.5"
}

// https://stackoverflow.com/questions/55725574/how-to-conditionally-accept-gradle-build-scan-plugin-terms-of-service-in-kotlin/56634703#56634703
develocity {
    buildScan {
        termsOfUseUrl = "https://gradle.com/help/legal-terms-of-use"
        termsOfUseAgree = "yes"
        // If you don't need to auto-publish the build scan, uncomment it.
        // publishing.onlyIf { false }
    }
}

rootProject.name = "sim-file-replayer"
include("app")
