// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: linoleum-ltlss/tracing.proto

package io.github.demiourgoi.linoleum.ltlss;

public final class Tracing {
  private Tracing() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_demiourgoi_linoleum_ltlss_SpanInfo_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_demiourgoi_linoleum_ltlss_SpanInfo_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\034linoleum-ltlss/tracing.proto\022\031demiourg" +
      "oi.linoleum.ltlss\032(opentelemetry/proto/t" +
      "race/v1/trace.proto\032*opentelemetry/proto" +
      "/common/v1/common.proto\032.opentelemetry/p" +
      "roto/resource/v1/resource.proto\"\364\001\n\010Span" +
      "Info\0220\n\004span\030\001 \001(\0132\".opentelemetry.proto" +
      ".trace.v1.Span\022B\n\005scope\030\002 \001(\01323.opentele" +
      "metry.proto.common.v1.InstrumentationSco" +
      "pe\022\030\n\020scope_schema_url\030\003 \001(\t\022;\n\010resource" +
      "\030\004 \001(\0132).opentelemetry.proto.resource.v1" +
      ".Resource\022\033\n\023resource_schema_url\030\005 \001(\tB\'" +
      "\n#io.github.demiourgoi.linoleum.ltlssP\001b" +
      "\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          io.opentelemetry.proto.trace.v1.TraceProto.getDescriptor(),
          io.opentelemetry.proto.common.v1.CommonProto.getDescriptor(),
          io.opentelemetry.proto.resource.v1.ResourceProto.getDescriptor(),
        });
    internal_static_demiourgoi_linoleum_ltlss_SpanInfo_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_demiourgoi_linoleum_ltlss_SpanInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_demiourgoi_linoleum_ltlss_SpanInfo_descriptor,
        new java.lang.String[] { "Span", "Scope", "ScopeSchemaUrl", "Resource", "ResourceSchemaUrl", });
    io.opentelemetry.proto.trace.v1.TraceProto.getDescriptor();
    io.opentelemetry.proto.common.v1.CommonProto.getDescriptor();
    io.opentelemetry.proto.resource.v1.ResourceProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
