/*
 * This source file was generated by the Gradle 'init' task
 */
package es.ucm.fdi.linoleum.tools.simreplayer

import kotlin.test.Test
import kotlin.test.assertNotNull

class AppTest {
    @Test fun appCanProvideOtel() {
        val sdk = provideOtel()
        assertNotNull(sdk)
    }
}
