/*
 * This source file was generated by the Gradle 'init' task
 */
package es.ucm.fdi.linoleum.tools.simreplayer

import kotlinx.serialization.Serializable
import kotlinx.serialization.json.Json
import kotlinx.serialization.encodeToString

import io.opentelemetry.api.OpenTelemetry
import io.opentelemetry.sdk.autoconfigure.AutoConfiguredOpenTelemetrySdk
import io.opentelemetry.api.common.AttributeKey
import io.opentelemetry.context.Context
import io.opentelemetry.context.ContextKey
import io.opentelemetry.api.trace.Span
import io.opentelemetry.api.trace.SpanKind
import io.opentelemetry.api.trace.StatusCode
import io.opentelemetry.api.trace.Tracer
import io.opentelemetry.context.Scope

private const val SCOPE_NAME = "es.ucm.fdi.linoleum.tools.simreplayer"
private const val SCOPE_VERSION = "0.1.0"
private const val SCOPE_SCHEMA_URL = "https://demiourgoi.github.io"

/** A simulated trace span
 *
 * @property parentId Id of the span that is the parent of this span
 * @property startTimeOffsetMillis How much to wait since the start of the replay to start this span. The parent
 * trace is created on its first span
 * @property durationMillis How much to wait since the span is created to close the span
 * */
@Serializable
data class SimSpan(
    val spanId: SimSpanId, val parentId: SimSpanId,
    val spanName: String, val spanKind: SpanKind=SpanKind.INTERNAL,
    val startTimeOffsetMillis: Long,
    val durationMillis: Long,
    val attributes: Map<String, String> = emptyMap<String, String>()) {

    companion object {
        fun fromJsonStr(jsonStr: String): SimSpan = Json.decodeFromString<SimSpan>(jsonStr)
    }

    fun toJsonStr(): String = Json.encodeToString(this)
}

/**
 * Id of a span in the simulation. These are arbitrary ids that won't be respected when emitting the trace
 * as the OTEL SDK will autogenerate new trace and span ids
 * A SimSpanId with an empty spanId is used for as the parentId of the first span of a trace.
 * */
@Serializable
data class SimSpanId(val traceId: String, val spanId: String? = null)


/*
* TODO for reaply
* - order by time: be explicit about assumption of whether or not we allow spans to happen at the same millis
* - create trace on first span found; also handle wait for next span. Grouping by trace and short the spans in advance
*   might be useful. Consider using some kind of executor service for this
* - signal errors due to spans emitted late: log to mark this
* - Create unit test with an OTEL provider that does nothing: detect spans emitted late with a mock logger. Usa
* https://mockk.io/ for idiomatic mocking
* * Precondition: each SimSpanId is unique in a simulation file. spanName doesn't need to be
* * Precondition: each trace has a single root span that is a span with null parentId.spanId, that is also
* the span with lowest startTimeOffsetMillis
* */


/**
 * @return a suitable open telemetry API implementation, typically a configured
 * OTEL SDK instance
 * */
fun provideOtel(): OpenTelemetry {
    // https://opentelemetry.io/docs/languages/java/configuration/#zero-code-sdk-autoconfigure
    return AutoConfiguredOpenTelemetrySdk.initialize().openTelemetrySdk
}

fun provideTracer(otel: OpenTelemetry): Tracer {
    return otel.tracerProvider
        .tracerBuilder(SCOPE_NAME)
        .setInstrumentationVersion(SCOPE_VERSION)
        .setSchemaUrl(SCOPE_SCHEMA_URL)
        .build()
}

fun waitForSpanRecording(span: Span) {
    while (!span.isRecording) {
        println("waiting for span to get ready to record")
        Thread.sleep(500)
    }
    println("span ready to record!")
}

fun sendSomeArbitraryTraces(): Unit {
    val otel = provideOtel()
    val tracer = provideTracer(otel)

    val context = Context.current()
        .with(ContextKey.named<String>("fooCtxKey"), "barCtxKey")

    val span = tracer.spanBuilder("Hello-span")
        .setSpanKind(SpanKind.INTERNAL)
        .setAttribute(AttributeKey.stringKey("${SCOPE_NAME}.foo"),"bar")
        .setAttribute(AttributeKey.stringKey("${SCOPE_NAME}.qux"),"baz")
        .setParent(context)
        .startSpan()
    val ctxWithParentSpan = span.storeInContext(context)
    try {
        waitForSpanRecording(span)

        val childSpan = tracer.spanBuilder("child span")
            .setParent(ctxWithParentSpan)
            .startSpan()
        var childSpanScope: Scope? = null
        try {
            // only keeping this reference so we can close it later, and pop from the
            // stack in `Context.current()`
            childSpanScope = childSpan.makeCurrent()

            val grandSonSpan = tracer.spanBuilder("grandson")
                .setAttribute(AttributeKey.stringKey("${SCOPE_NAME}.grandSonFoo"), "bar")
                .startSpan()
            grandSonSpan.end()

        } finally {
            childSpanScope?.close()
            childSpan.end()
        }

        span.addEvent("foo event")
        span.setStatus(StatusCode.OK, "all good man")

    } finally {
        span.end()
        val spanCtx = span.spanContext
        println("Closed span with span id ${spanCtx.spanId}, trace id ${spanCtx.traceId}")
    }
}

fun main() {
    sendSomeArbitraryTraces()
    println("Bye")
}
