name: sim_file_replayer

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./sim_file_replayer
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 20
        uses: actions/setup-java@v4
        with:
          java-version: '20'
          distribution: 'temurin'

      # Configure Gradle for optimal use in GitHub Actions, including caching of downloaded dependencies.
      # See: https://github.com/gradle/actions/blob/main/setup-gradle/README.md
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@af1da67850ed9a4cedd57bfd976089dd991e2582 # v4.0.0

      # See the Gradle build scan link in the "build summary" of the github actions run
      - name: Build with Gradle Wrapper
        run: chmod +x gradlew && make release EXTRA_BUILD_ARGS=--scan

      # https://docs.github.com/en/actions/writing-workflows/choosing-what-your-workflow-does/storing-and-sharing-data-from-a-workflow
      # https://github.com/actions/upload-artifact/issues/232  The upload-artifact action does not use the working-directory setting
      - name: Archive build reports
        uses: actions/upload-artifact@v4
        with:
          name: build-reports
          path: sim_file_replayer/app/build/reports
