// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: linoleum-ltlss/tracing.proto

package es.ucm.fdi.demiourgoi.linoleum.ltlss;

public interface SpanInfoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:demiourgoi.linoleum.ltlss.SpanInfo)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.opentelemetry.proto.trace.v1.Span span = 1;</code>
   * @return Whether the span field is set.
   */
  boolean hasSpan();
  /**
   * <code>.opentelemetry.proto.trace.v1.Span span = 1;</code>
   * @return The span.
   */
  io.opentelemetry.proto.trace.v1.Span getSpan();
  /**
   * <code>.opentelemetry.proto.trace.v1.Span span = 1;</code>
   */
  io.opentelemetry.proto.trace.v1.SpanOrBuilder getSpanOrBuilder();

  /**
   * <code>.opentelemetry.proto.common.v1.InstrumentationScope scope = 2;</code>
   * @return Whether the scope field is set.
   */
  boolean hasScope();
  /**
   * <code>.opentelemetry.proto.common.v1.InstrumentationScope scope = 2;</code>
   * @return The scope.
   */
  io.opentelemetry.proto.common.v1.InstrumentationScope getScope();
  /**
   * <code>.opentelemetry.proto.common.v1.InstrumentationScope scope = 2;</code>
   */
  io.opentelemetry.proto.common.v1.InstrumentationScopeOrBuilder getScopeOrBuilder();

  /**
   * <pre>
   * field schema_url in the parent ScopeSpans message
   * </pre>
   *
   * <code>string scope_schema_url = 3;</code>
   * @return The scopeSchemaUrl.
   */
  java.lang.String getScopeSchemaUrl();
  /**
   * <pre>
   * field schema_url in the parent ScopeSpans message
   * </pre>
   *
   * <code>string scope_schema_url = 3;</code>
   * @return The bytes for scopeSchemaUrl.
   */
  com.google.protobuf.ByteString
      getScopeSchemaUrlBytes();

  /**
   * <code>.opentelemetry.proto.resource.v1.Resource resource = 4;</code>
   * @return Whether the resource field is set.
   */
  boolean hasResource();
  /**
   * <code>.opentelemetry.proto.resource.v1.Resource resource = 4;</code>
   * @return The resource.
   */
  io.opentelemetry.proto.resource.v1.Resource getResource();
  /**
   * <code>.opentelemetry.proto.resource.v1.Resource resource = 4;</code>
   */
  io.opentelemetry.proto.resource.v1.ResourceOrBuilder getResourceOrBuilder();

  /**
   * <pre>
   * field schema_url in the parent ResourceSpans message
   * </pre>
   *
   * <code>string resource_schema_url = 5;</code>
   * @return The resourceSchemaUrl.
   */
  java.lang.String getResourceSchemaUrl();
  /**
   * <pre>
   * field schema_url in the parent ResourceSpans message
   * </pre>
   *
   * <code>string resource_schema_url = 5;</code>
   * @return The bytes for resourceSchemaUrl.
   */
  com.google.protobuf.ByteString
      getResourceSchemaUrlBytes();
}
